name: Swing Music
package: cloud.lazycat.app.swing-music
version: 2.1.4
min_os_version: 1.3.8
description: 一款美观、自托管的音乐播放器
homepage: https://github.com/swingmx/swingmusic
author: swingmx
application:
  subdomain: swing-music
  multi_instance: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://swingmusic:1970

services:
  swingmusic:
    #  ghcr.io/swingmx/swingmusic:v2.1.4
    image: registry.lazycat.cloud/czyt/swingmx/swingmusic:605bda19b59f0ab6
    binds:
      - /lzcapp/document/{{.U.music_dir_name}}:/music
      - /lzcapp/var/config:/config

ext_config:
  enable_document_access: true
  enable_media_access: true

locales:
  zh:
    name: "Swing Music"
    description: "一款美观、自托管的音乐播放器"

  en:
    name: "Swing Music"
    description: "A beautiful, self-hosted music player for your local audio files."
